language: swift
osx_image: xcode9.4
xcode_project: WeatherInfo.xcworkspace
xcode_scheme: WeatherInfo
xcode_sdk: iphonesimulator11.4
os: osx
#branches:
#  only:
#    - develop
 #   - master
    
cache:
  - bundler
  - cocoapods
podfile: Podfile

env:
  - UPLOAD_IOS_SNAPSHOT_BUCKET_NAME=eigen-ci UPLOAD_IOS_SNAPSHOT_BUCKET_PR...
  - PROJECTNAME=WeatherInfo

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - 'gem install fastlane --no-ri --no-rdoc --no-document'
  - pod install
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true

install: true
before_script:
  - gem install cocoapods
  - gem install colorize
  - gem install CFPropertyList

script:
  #- set -o pipefail 
 # - xcodebuild test -enableCodeCoverage YES -workspace ${PROJECT_NAME}.xcworkspace -scheme ${PROJECT_NAME} -sdk iphonesimulator11.4 ONLY_ACTIVE_ARCH=NO | xcpretty
  - fastlane scan -s ${PROJECT_NAME}
